remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
logo: /new_me.jpg
title: Rafał Stottko
social_links:
  - name: GitHub
    url: https://github.com/twoje-konto
  - name: LinkedIn
    url: https://www.linkedin.com/in/twoje-konto/
  - name: Twitter
    url: https://twitter.com/twoje-konto
#google_analytics: [Your Google Analytics tracking ID]
